General: 
  nTimesteps: 192 # 8 representative days x 24 hours
  nReprDays: 8 # days
  nDays: 365 # days
  nYears: 1 # years
  sigmaCM: 1 # CM switch

ADMM:
  rho_EOM: 1.2 # rho ADMM penalty term, EOM
  rho_CM: 1 # rho ADMM penalty term, CM
  max_iter: 5000
  epsilon: 0.1 # 0.1 # stopping criterion - tolerance on "accuracy" with which the coupling constraints are satisfied. Applied to dual and primal residuals.
  CircularBufferSize: 5 # number of iterations for which data will be retained, should be at least 2 and less than max_iter

EOM: 
  parameter_A: 1 # dummy, not used 


Consumers: # consumers by zones
  A:
    WTP: 4000 # Max clearing price (€/MWh)
    D: "A" # Demand timeseries that needs to be picked up
    ela: 0.04 # fraction of demand that is elastic # 0.04 at WTP = 4000, 0.2 at WTP = 20000
    sigmaCM: 1 
    NodeShare:
      n1: 0.5
      n2: 0.5

  B:
    WTP: 4000 #4000.0 # Max clearing price (€/MWh)
    D: "B" # Timeseries that needs to be picked up
    ela: 0.04 # fraction of demand that is elastic
    sigmaCM: 1
    NodeShare:
        n3: 1.0

  C:
     WTP: 4000 #4000.0 # Max clearing price (€/MWh)
     D: "C" # Timeseries that needs to be picked up
     ela: 0.04 # fraction of demand that is elastic
     sigmaCM: 1
     NodeShare:
         n4: 1.0

Generators: 
  # OPEX are parametrized as a/2 x g^2 + b x g
  A: 
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 20 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 190000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n1: 0.5
          n2: 0.5

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 55 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 110000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n1: 0.5
          n2: 0.5

    Peak:
      a: 0.04 # (€/MWh)^2
      b: 100 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 60000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n1: 0.5
          n2: 0.5

    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 13700 # MW
      I: 300000 # €/MW-year - annualized investment cost
      max_cap: 13700 # MW - maximum capacity
      AF: "A"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n1: 0.5
          n2: 0.5
    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 15403 # MW
      I: 300000 # k€/MW-year - annualized investment cost
      max_cap: 15403 # MW - maximum capacity
      AF: "A"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n1: 0.5
          n2: 0.5
  B:
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 20 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 190000 # €/MW-year - annualized investment cost (convert to €/MW-year?)
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n3: 1.0

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 55 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 110000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n3: 1.0

    Peak:
      a: 0.06 # (€/MWh)^2
      b: 100 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 70000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n3: 1.0

    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 5315 # MW
      I: 300000 # €/MW-year - annualized investment cost
      max_cap: 5315 # MW - maximum capacity
      AF: "B"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n3: 1.0

    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 8788 # MW
      I: 300000 # €/MW-year - annualized investment cost
      max_cap: 8788 # MW - maximum capacity
      AF: "B"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n3: 1.0

  C: 
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 20 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 190000 # €/MW-year - annualized investment cost (convert to €/MW-year?)
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n4: 1.0

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 55 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 110000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n4: 1.0

    Peak:
      a: 0.08 # (€/MWh)^2
      b: 100 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 80000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      DF: 1.0 # derating factor
      NodeShare:
          n4: 1.0

    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 8300 # MW
      I: 300000.2 # €/MW-year - annualized investment cost
      max_cap: 8300 # MW - maximum capacity
      AF: "C"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n4: 1.0

    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 18662 # MW
      I: 300000.2 # €/MW-year - annualized investment cost
      max_cap: 18662 # MW - maximum capacity
      AF: "C"
      sigmaCM: 0
      DF: 0 # derating factor
      NodeShare:
          n4: 1.0

CM:
  A:
    # explicit/implicit/capacity target for zone A
    capacity_target: 17629.87 # "FB-D"/ "ATC"  - 16748.4 / "noCBP" - 17629.87 / "implicit" - 17629.87
    price_target: 60000    # €/MW (price target for zone A - CONE)
    capacity_margin: 0.1     # 10% capacity margin
    min_price: -10000000
    max_price: 10000000
    D: "A" #
  B:
    capacity_target: 15468.46  # "FB-D"/ "ATC" - 14695 / "noCBP" - 15468.46 / "implicit" - 14379.77
    price_target: 70000
    capacity_margin: 0.1
    min_price: -10000000
    max_price: 10000000
    D: "B"
  C:
    capacity_target: 17169.93 # "FB-D"/ "ATC" - 16311.4 / "noCBP" - 17169.93 / "implicit" - 12142.21 
    price_target: 80000
    capacity_margin: 0.1
    min_price: -10000000
    max_price: 10000000
    D: "C"

Network:
  ZoneMap:
    A: [n1, n2]
    B: [n3]
    C: [n4]
    
  TCONNECT:
    - [A, C]
    - [C, B]
    - [B, A]

  ATC:
    A:
      C: [2357.4, -2232.4]  # [forward limit, backward limit]
    C:
      B: [877.1, -716]
    B: 
      A: [1472, -1085.7]

# ATC: [(3000.0000000000036, -3000.0), (655.7499999999674, -655.75), (1282.9500000000007, -344.2500000000018)]

  reserve_cost: 1000000 # €/MW-year
    

  nLines: 4
  nScenarios: 4
  lines: "lines"  # lines dataframe
  ptdf: "ATC"  # PTDF dataframe
  nodal_ptdf: "nodal_ptdf"  # nodal PTDF dataframe
  coupling: "ATC"  # "FB" / "ATC" / "noCBP" / "implicit" / "none"
  # IC_reserve: 500000 # €/MW-year higher than the highest fixed cost
  # MC_reserve: 50000 # €/MWh higher than voll


# same variable cost for all generators.